import {
  useState
} from 'react'
import tuberculosis from './img/answer/tuberculosis.png';
import GramMethod from './img/answer/GramMethod.png';
import disinfection from './img/answer/disinfection.png';
import cilia from './img/answer/cilia.png';
import Chlamydiae from './img/answer/Chlamydiae.png';
import bacteriaStructure from './img/answer/bacteriaStructure.png';
import antiStain from './img/answer/antiStain.png';

// import from './img/answer/.png'

export const useQuestionList = () => {
  const appName = 'anywhere-microbiology'
  const jpName = '微生物感染症学'
  const [questionList, setQuestionList] = useState([
    // ここに問題のリストを記述(選択式の場合は[0]に正解択をいれた配列をつくる)
    {
      groupTag: '授業中',
      groupContents: [{
          detailInfo: '4/26',
          questionImg: [],
          questionSentence: '抗菌薬と作用機序の組み合わせで適切なものはどれか',
          answerImg: [],
          choices: [
            'シプロフロキサシン - DNA合成阻害',
            'アンピシリン - タンパク質合成阻害',
            'ミノサイクリン - 細胞膜合成阻害',
            'アミカシン - 細胞壁合成阻害',
          ],
          answer: 'シプロフロキサシン - DNA合成阻害',
          commentary: 'シプロフロキサシンはニューキノロン系薬で、拡散合成を阻害する。アンピシリンはβラクタム系薬で、細胞壁合成を阻害する。ミノサイクリンはテトラサイクリン系薬で、タンパク合成を阻害する。アミカシンはアミノグリコシド系で、タンパク合成を阻害する。',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】ウイルス粒子にはDNAまたはRNAが存在する',
          answerImg: [],
          answer: '正しい',
          commentary: 'RNAが多い',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】細菌に感染するウイルスが存在する',
          answerImg: [],
          answer: '正しい',
          commentary: 'バクテリオファージ',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】ウイルスは宿主細胞認識機構をもつ',
          answerImg: [],
          answer: '正しい',
          commentary: 'インフルエンザであればシアル酸、コロナウイルスであればACE2',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】ウイルスの感染過程に、宿主細胞のプロテアーゼが関与する場合がある',
          answerImg: [],
          answer: '正しい',
          commentary: '脱殻、タンパク質生成など',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】潜伏感染には水痘・帯状疱疹ウイルスがある',
          answerImg: [],
          answer: '正しい',
          commentary: '持続感染のひとつ。',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】抗病原性鳥インフルエンザウイルスは抗原不連続変異により出現する',
          answerImg: [],
          answer: '正しい',
          commentary: 'HAとNAの組み合わせでH3などができた',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】抗生物質により、ウイルスを死滅させることができる',
          answerImg: [],
          answer: 'できない',
          commentary: '抗生物質はバクテリアだけ。抗ウイルス薬はほとんどの場合製造が難しい。',
        },
        {
          detailInfo: '5/24スライド',
          questionImg: [],
          questionSentence: '【正誤問題】新型コロナウイルスはエンベロープをもつため、消毒薬などに抵抗性が高い。',
          answerImg: [],
          answer: '誤り',
          commentary: 'エンベロープがあるから、アルコールや石鹼に溶け死滅する。',
        },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
      ],
    }, {
      groupTag: "2021 TBL",
      groupContents: [{
          detailInfo: '',
          questionImg: [],
          questionSentence: '芽胞を形成する菌に有効でない滅菌・消毒法はどれか(複数選択可)',
          answerImg: [disinfection],
          choices: ["酸化エチレンガス滅菌", "アルコール", "高圧蒸気滅菌", "過酸化水素低温ガスプラズマ滅菌", "界面活性剤"],
          answer: 'アルコール、界面活性剤',
          commentary: '芽胞を形成する菌に有効なのは滅菌あり、酸化エチレンガス滅菌、高圧蒸気滅菌（オートクレーブ）、過酸化水素低温ガスプラズマ滅菌は大量の芽胞を含む、全ての微生物を殺滅あるいは除去することができる。アルコールは中水準消毒であり、芽胞を除く結核菌、その他の細菌、ほとんどのウイルスや真菌を殺滅させるが、芽胞を形成する菌には有効ではない。界面活性剤（石鹸）は低水準消毒であり、ほとんどの細菌や真菌、一部のウイルスを殺滅させるが、結核菌や芽胞は殺滅させず、芽胞を形成する菌には有効ではない。',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '次の文章について正しいのはどれか（複数選択可）',
          answerImg: [],
          choices: ["北里柴三郎は1987年に赤痢菌の培養に成功し、赤痢菌の学名は北里の名前が由来である", "ジェンナーは、埃が外部から侵入しえない、白鳥の首型フラスコを用いて自然発生説の否定に成功する", "志賀潔は破傷風菌の純粋培養に成功し、ペスト菌を発見した", "感染症の病原体を特定する際の指針の一つとしてコッホの4原則が定められた", "中野竜一は、新型コロナウイルスを不活化する新規複合酸化物の開発に携わった。"],
          answer: '4と5が正しい',
          commentary: '志賀潔は赤痢菌の純培養に成功し、赤痢菌をShigellaと名付けた。これは病原菌の学名に日本人の名前がついている唯一の菌名である。パスツールは煮沸した肉汁を埃の入らない「白鳥の首型フラスコ」に入れておけば腐敗しないことを示し、当時信じられていた自然発生説を否定した。北里柴三郎は破傷風菌の純粋培養に成功し、ペスト菌を発見した。　コッホの4原則は、1.ある一定の病気には一定の微生物が見いだされること、2.その微生物を分離できること、3.分離した微生物を感受性のある動物に感染させて同じ病気を起こせること、4.そしてその病巣部から同じ微生物が分離されること　を定めた感染症の指針。',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'グラム陰性菌とグラム陽性菌について大きな特徴の違いはどれか（複数選択可）',
          answerImg: [GramMethod],
          choices: ["ペプチドグリカン層の厚み", "リポ多糖体の有無", "鞭毛の数", "リン脂質の有無", "プラスミドの有無"],
          answer: 'ペプチドグリカン層の厚み、リポ多糖体の有無、リン脂質の有無',
          commentary: '厚いペプチドグリカン層がグラム染色によって染色される。リポ多糖体はLPSとも。例えばグラム陰性桿菌の大腸菌は鞭毛を持たないし、鞭毛の数がグラム染色で染め分けられているわけではない。プラスミドは染色体外の環状DNAのことで、陽性菌も陰性菌も両方持っている。',
        },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence: '内毒素・外毒素のどれか',
        //   answerImg: [],
        //   choices: ["", "", "", "", ""],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence: 'どれか',
        //   answerImg: [],
        //   choices: ["", "", "", "", ""],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence: 'どれか',
        //   answerImg: [],
        //   choices: ["", "", "", "", ""],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence: 'どれか',
        //   answerImg: [],
        //   choices: ["", "", "", "", ""],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence: 'どれか',
        //   answerImg: [],
        //   choices: ["", "", "", "", ""],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence: 'どれか',
        //   answerImg: [],
        //   choices: ["", "", "", "", ""],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence: 'どれか',
        //   answerImg: [],
        //   choices: ["", "", "", "", ""],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
      ]
    }, {
      groupTag: "2022本試験",
      groupContents: [{
          detailInfo: '',
          questionImg: [],
          questionSentence: '細菌について正しいのはどれか',
          choices: ["細菌にはリボソームが存在しない", "結核菌は芽胞形成菌である", "プラスミドを接合伝達させるためには性腺毛を必要とする", "クラミジアにはグラム染色が有用である", "グラム染色の接合性の違いは莢膜による"],
          answerImg: [bacteriaStructure, tuberculosis, cilia, Chlamydiae, GramMethod],
          answer: 'プラスミドを接合伝達させるためには性線毛を必要とする',
          commentary: '細菌はタンパク合成のためのリボソームやプラスミドを保有している。性腺毛を持っている細菌はプラスミドの接合伝達によってペニシリナーゼやESBL、MBL産生遺伝子を伝達し薬剤耐性を伝播することがある。結核菌は外側をミコール酸で覆われているその特徴から一般的な抗菌薬が無効であるため、抗結核薬が使用される。結核はその他鞭毛・莢膜を持たず、通常の染色法では染まりにくい特徴も持っている。クラミジアはグラム染色で染色されるペプチドグリカン層を持っていない。',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '外毒素の中で耐熱性のエンテロトキシンを放出する菌はどれか',
          choices: ["黄色ブドウ球菌", "ウェルシュ菌", "サルモネラ菌", "セレウス菌", "大腸菌"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'グラム陰性菌の存在し、グラム陽性菌に存在しないのはどれか',
          choices: ["莢膜", "線毛", "リポ多糖", "ポーリン", "プラスミド","ペプチドグリカン"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '微生物に該当するのは次のうちどれか',
          choices: ["放線菌", "細菌類", "菌界", "原生生物界", "古細菌"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '細菌について誤っているものは次のうちどれか',
          choices: ["DNAに含まれる塩基はグアニン・アデニン・シトシン・チミンである", "プラスミドは細胞内で独立して存在・増殖できる", "染色体は核膜内にある", "細胞内で増殖したファージは成熟すると、溶菌酵素により菌体を壊して放出される", "プロモーターはリプレッサーと結合することで、構造遺伝子群の発現を抑制する"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'ファージのDNAが細菌の染色体DNAに組み込まれた状態をなんというか',
          choices: ["カプシド", "ビリオン", "プロファージ", "マクロファージ", "トランスポゾン"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '通性嫌気性の説明として正しいのはどれか',
          choices: ["酸素が存在しないと増殖できない", "酸素が存在すると増殖できない", "酸素の存在の有無にかかわらず増殖できる", "二酸化炭素がソンジアすると増殖できない", "二酸化炭素が存在すると増殖できる"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'グラム陽性桿菌について正しいのはどれか',
          choices: ["グラム陽性桿菌のうち、リステリア属は嫌気性菌である", "破傷風金に感染する場合、咽頭・属桃に白から灰白色の偽膜形成が見られる", "人が感染する炭疽菌は95%が皮膚炭疽であり、家畜を扱う人で発症することが多い", "ボツリヌス菌は芽胞を形成する", "ウェルシュ菌は嫌気性芽胞形成菌であり、シチューなどで食中毒をきたす"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '菌交代現象によって発症するのはどれか',
          choices: ["腸結核", "カンピロバクター腸炎", "クリプトスポリジウム症", "サイトメガロウイルス食道炎", "クロストリジウム・ディフィシル腸炎"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '体育の授業中にサッカーをしていた際、転倒し擦り傷を負った。４日後、発語・構音障害、痙笑などの症状が出現した。上記の症状を起こした原因菌として最も考えられるのはどれか',
          choices: ["ウェルシュ菌", "ボツリヌス菌", "破傷風菌", "サルモネラ菌", "ジフテリア菌"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '黄色ブドウ球菌が関連する病原性として当てはまるものはどれか',
          choices: ["食中毒", "毒素性ショック症候群", "表皮剥脱性皮膚炎", "化膿性炎症", "アトピー性皮膚炎"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '細胞毒に該当する毒素はどれか',
          choices: ["コレラ毒素", "百日咳毒素", "ジフテリア毒素", "テタノスパスミン", "腸炎ビブリオ毒素"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '肺炎球菌について誤っているものはどれか',
          choices: ["食中毒の原因菌としては五番目に多い", "成人の市中肺炎で最も多い起炎菌である", "肺炎から菌血症を合併しやすい", "血液寒天培地上でβ溶血を示す", "予防として生ワクチンが小児にたいして用いられる"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'メチシリン耐性黄色ブドウ球菌(MRSA)について正しいのはどれか',
          choices: ["院内感染の主要な起炎菌の一つである", "vanA遺伝子の獲得により耐性化する", "メチシリン以外のβラクタム系抗菌薬にも耐性を示す", "MRSAの治療薬として、バンコマイシンが有効である", "MRSAは人のみならず、家畜やペットからも検出される"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '新生児髄膜炎患者の髄液からグラム陽性連鎖球菌が分離された。起因菌として考えられるのはどれか',
          choices: ["Staphylococcus epidermidis", "Streptococcus agalactiae", "Enterococcus faecalis", "Peptococcus niger", "Peptostreptococcus anaerobius"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '薬剤耐性菌について正しいのはどれか',
          choices: ["薬剤耐性出現のメカニズムには、自然耐性と獲得耐性がある", "抗菌薬使用薬剤耐性菌に関係性はない", "世界における薬剤獲得菌に直接起因する死亡者数は、年間100万人以上である", "MRSAは通常の黄色ブドウ球菌に比較して感染力が高い", "番細い真耐性黄色ブドウ球菌MRSAは、日本ではまだ分離されたことはない","ウイルスにも抗ウイルス薬耐性が出現している"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '70歳女性、近くの大学病院で慢性腎不全の治療を受けていた。軽快に伴い退院し、以後の加療 を行っていただきたい旨が書かれた紹介状を持って受診された。入院中に便からバンコマイシン耐性腸球菌(VRE)が検出されたと記載されている。入院中から現在まで下痢や発熱は認め ていない。適切な対応はどれか。',
          choices: ["受診の際は常にマスクを着用させる", " 診察の際はガウンを着用する", "トイレのあとはアルコールで手指消毒してもらう", "VRE対策ができないため大学病院へ戻す", "リネゾリドを内服させる"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'バンコマイシン耐性腸球菌に有効な薬はどれか',
          choices: ["リネソリド", "コリスチン", "バンコマイシン", "テイコプラニン", "アミノグリコシド"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '薬剤耐性菌が発生・伝播する原因はどれか',
          choices: ["抗菌薬の過剰投与・過剰処方", "新しい抗菌薬の開発の遅れ", "MRSAやVREの耐性菌が発生する要因は、抗菌薬の使用による", "医療機関における不十分な院内感染対策", "MRSAなど動物由来とされるものもある"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '薬剤耐性グラム陽性菌について誤っているものはどれか',
          choices: ["日本はペニシリン耐性肺炎球菌の割合が高い", "ペニシリン耐性肺炎球菌の耐性機構は、結合親和性の低下である。", "バンコマイシン耐性腸球菌は、米国で多く分離され、家畜からも分離される", "バンコマイシン耐性腸球菌は、近年奈良県において高頻度に分離される", "メチシリン耐性黄色ブドウ球菌は、抗菌薬を使用することで容易に発生する","メチシリン耐性黄色ブドウ球菌は、人のみならず、家畜からも分離される"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'ウイルス感染細胞に起こりうる変化でないのはどれか',
          choices: ["ガン化", "細胞表面の変化", "封入体の形成", "細胞変性効果", "インターフェロン産生低下"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '我が国で使用されている生ワクチンはどれか',
          choices: ["BCG", "麻疹", "コレラ", "日本脳炎", "インフルエンザ"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'レトロウイルスに該当するものとして正しいのはどれか',
          choices: ["急性感染", "逆転写酵素", "DNAウイルス", "人のがんウイルス", "ヒトT細胞白血病ウイルス"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '五類感染症に該当するものはどれか',
          choices: ["バンコマイシン耐性腸球菌", "ペニシリン耐性腸炎球菌", "メチシリン耐性黄色ブドウ球菌", "多剤耐性アシネトバクター", "ESBL産生腸内細菌科","カルバペネム耐性腸内細菌科"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'ウイルスの説明で正しいのはどれか',
          choices: ["宿主細胞内のみで増殖する", "エネルギー産生機構を持たない", "人工培地で培養できる", "多くは種特異的、組織特異的に感染する", "ウイルスゲノムが宿主細胞のゲノムに組み込まれることがある"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '感染様式について正しいのはどれか',
          choices: ["水痘は性交感染する", "ポリオウイルスは発症に媒介動物が関与する", "RSウイルス感染症は母子感染症を引き起こす", "ノロウイルスは血液を介して院内感染が起こる", "重症熱性血小板減少症候群(SFTS)は、主にマダニに噛まれることにより感染する"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'インフルエンザウイルスについて、誤っているものはどれか',
          choices: ["DNAウイルスなので抗原変異を起こしにくい", "表面に赤血球凝集素をもつ", "受容体は気管上皮のシアル酸である", "B型インフルエンザとC型インフルエンザはヒトだけを宿主とする", "季節性インフルエンザは抗原連続変異によりHAやNAが変異する","エンベロープを持つため、消毒薬などに抵抗性が高い"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '次の図は我が国のRSウイルス患者数の推移を示している。2021年に流行が認められたが、同様に2022年において我が国でその患者数が増大することが予想される感染症はどれか。',
          choices: ["狂犬病", "水痘・帯状発疹", "エボラ出血熱", "インフルエンザウイルス", "EBウイルス","ヒトヘルペスウイルス"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '実習で行った操作について正しいのはどれか',
          choices: ["白金耳は火炎滅菌して実験を行った", "換気をよくする必要があり、窓を開けて実験を行った", "光学顕微鏡で観察する際、無水アルコールを滴下してから検鏡した", "生化学的性状試験により菌種を同定した", "薬剤感受性について、薬剤ディスクの周辺の阻止円の直径の長さにより判別した"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: 'DHL寒天培地に含まれる細菌培養の選択性を示すための物質はつぎのうちどれか。',
          choices: ["胆汁酸塩", "酵母抽出物", "塩化ナトリウム", "ニュートラルレッド", "フェノールレッド"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '実習で扱った細菌として正しいのはどれか',
          choices: ["大腸菌はグラム染色をすると、赤色（ピンク色）の球菌で観察された", "黄色ブドウ球菌を過酸化水素水と混ぜると激しく泡が発生した", "表皮ブドウ球菌(S.epidermidis)をウサギプラズマに入った試験管に接種し、一晩37℃で培養すると凝固した", "CTX(Cefotaxime)に耐性を示した腸内細菌科において、CTXC(Cefotaxime/Clavulanate)の阻止円が≧5mm拡張していればESBLと判定する", "CFX(Cefoxitin)に耐性を示した黄色ブドウ球菌について、MRSAと判定する。"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '培地について正しいことを示しているのはどれか',
          choices: ["大腸菌や肺炎球菌は、DHL寒天培地上で赤色のコロニーであることが多い", "マンニット食塩寒天培地に対して、黄色ブドウ球菌は黄色を呈する", "マンニット食塩寒天培地にはニュートラルレッドが含まれる", "ミュラーヒントン寒天培地は選択制がなく、薬剤感受性試験に用いた", "手掌の消毒効果を確認するために、SCDLP寒天培地を用いた"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
                {
          detailInfo: '',
          questionImg: [],
          questionSentence: '肺炎について誤っているものはどれか',
          choices: ["高齢者の肺炎は誤嚥を元に発症することが多い", "現在我が国では肺炎による死亡者の95%以上が高齢者で占められている", "レジオネラ感染症では、ほとんどが急激に重症科するレジオネラ肺炎を発症するため、自然治癒することはない", "肺炎の原因として、感染性のもの（細菌性・ウイルス性・真菌など）と非感染性のもの（間質性肺炎）が挙げられる", "肺炎球菌ワクチンの成分は莢膜多頭体である"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '呼吸器疾患(肺炎）の原因となるウイルスはどれか',
          choices: ["ロタウイルス", "ノロウイルス", "ライノウイルス", "ヒトヘルペスウイルス6型", "アデノウイルス"],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },       
                 {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },
        {
          detailInfo: '',
          questionImg: [],
          questionSentence: '',
          choices: ["", "", "", "", ""],
          answerImg: [],
          answer: '',
          commentary: '',
        },

        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
        // {
        //   detailInfo: '',
        //   questionImg: [],
        //   questionSentence:
        //     '',
        //   answerImg: [],
        //   answer: '',
        //   commentary: '',
        // },
      ],
    },
  ])
  const showQuestionList = () => {
    return questionList
  }
  return {
    showQuestionList,
    appName,
    jpName,
  }
}